### ISSUE TITLE
Enable permanent links for specific calculator inputs

### ISSUE THREAD

**Issue by mathiasbynens** [xandjiji/exevo-pan#105]
I'd like to share my view of https://www.exevopan.com/calculators/exercise-weapons with a friend, without having to tell them to enter exactly the same values. Ideally this would be possible by encoding the input values in the URL, e.g.

```
https://www.exevopan.com/calculators/exercise-weapons?vocation=2&skill=magiclevel&currentSkill=39&targetSkill=40&percentageLeft=31.46&loyalty=3600
```

The Bazaar feature already supports this, e.g.

```
https://www.exevopan.com/?vocation=1&pvp=1&location=0&battleye=true&dummy=true&minLevel=584&maxLevel=1532
```

Please consider doing the same thing for the calculator pages.

**Comment by xandjiji** [comment]
done!

**Comment by xandjiji** [comment]
done!
