### ISSUE TITLE
Não é uma Issue e sim uma duvida sobre a tag 'Soul War Disponivel'

### ISSUE THREAD

**Issue by hotsoft-desenv3** [xandjiji/exevo-pan#146]
Qual a condição para ela aparecer?
Vejo que alguns leilões o personagem não fez a soul war e tem uns level como 550+ e ela nao aparece.
ja as vezes tem personagem com lvl 400 e tambem não fez e ela aparece.

exemplo de um que não aparece e mostra nas quests que ele não fez:
https://exevopan.com/pt/bazaar-history?auctionId=1048919

**Comment by xandjiji** [comment]
olá

- a tag de soulwar disponível aparecerá apenas para personagens lvl 400+ ([código](https://github.com/xandjiji/exevo-pan/blob/99c109d7afb00e2e4ced10b98529ebfe374fb251/packages/shared-utils/src/getCharacterTags.ts#L80-L85))
- já o filtro por personagens com soulwar disponível irá mostrar pesonagens lvl 250+, pois esse é o level minimo para se fazer a quest [(código)](https://github.com/xandjiji/exevo-pan/blob/99c109d7afb00e2e4ced10b98529ebfe374fb251/packages/auction-queries/src/Filtering/schemas/soulwar.ts#L14-L15) 

---

a gente optou por exibir a tag apenas para personagens lvl 400+. Personagens lvl 250~300 sem soulwar são muito comuns e exibir a tag para eles não seria tão relevante para o usuário. A ideia das tags é justamente sinalizar que o personagem possui algo de especial ✨

o personagem do seu exemplo não  completou a souwar, porém chegou a pegar a recompensa. O site oficial do jogo diz que ele **não** possui a flag de soulwar completa, mas ainda assim a gente sabe que ele chegou a pegar a recompensa (que é o mais importante para nós) por possuir a Revenant outfit

a gente prefere manter a lista de quests dos personagens espelhando o que é exibido no site oficial. Nossos algoritmos de coleta de dados buscam apenas se manterem sincronizados com a fonte da verdade (no caso, o site oficial). É somente no nosso front/back que a gente tenta inferir informações extras
