### ISSUE TITLE
Boss timer is off

### ISSUE THREAD

**Issue by mathiasbynens** [xandjiji/exevo-pan#155]
The boss tracker lists Dracola on Vunira as "no chance (expected in 1 day)", but my team just found and killed it anyway.

I think the boss tracker should update twice per 24 hours:

- once when the kill stats update (to update "recently killed")
- once when server save takes place (to update the boss countdowns)

**Comment by mathiasbynens** [comment]
For the record, [Tibia.com kill stats update daily around 04:00 CE(S)T](https://www.tibiaqa.com/26439/when-and-how-often-the-kill-statistics-are-updated?show=26440#a26440). So you might want to schedule the task to pull in new kill stats data for 04:30 CE(S)T. That’s 03:30 UTC during CET, and 02:30 UTC during CEST.

Then there’s server save, which happens at 10:00 CE(ST). Thus, you might want to schedule the task to update the boss countdowns at 10:30 CET or so, which is 09:30 UTC during CET and 08:30 UTC during CEST.

**Comment by xandjiji** [comment]
I'm double checking everything and indeed Dracola should have a ~6% spawn chance yesterday on Vunira. What time (UTC plz) was it when the page displayed "no chance" for Dracola for you?

I believe the page revalidation hook failed for some reason (it happened before) and it had stale data instead

I'll add measures to make sure it revalidates correctly in the future

**Comment by xandjiji** [comment]
by the way, your automations check every 10 minutes for kill statistics updates (I swear this is not overkill, Tibia.com is often very unreliable and the best way to get around it is to always try to be on sync with it 😅)

**Comment by mathiasbynens** [comment]
> I'm double checking everything and indeed Dracola should have a ~6% spawn chance yesterday on Vunira. What time (UTC plz) was it when the page displayed "no chance" for Dracola for you?

I posted this thread ~40 minutes after Dracola was found — so Exevo Pan was showing the wrong snapshot that day at 18:23 CET (17:23 UTC, or 2022-12-19T17:23:19Z) at least.


> by the way, our automations check every 10 minutes for kill statistics updates (I swear this is not overkill, Tibia.com is often very unreliable and the best way to get around it is to always try to be on sync with it 😅)

Oofff, that sounds wasteful :P Have you considered only retrying if something goes wrong? Have you considered using [the TibiaData API](https://tibiadata.com/) to work around the rate limiting (and to avoid the need to parse the HTML response yourself)? Anecdotally, I’m using TibiaData to pull in daily kill stats for https://github.com/tibiamaps/tibia-kill-stats *just once per day* and I haven’t had any issues.

**Comment by xandjiji** [comment]
For some reason, sometimes a few kill statistics pages will take longer to update:
![image](https://user-images.githubusercontent.com/11613697/227684434-fe883c7e-049a-43f5-983c-e8f3a646ccd2.png)

My scripts were not dealing correctly with this, and would sometimes use stale data to calculate the next day's estimates. I just released a fix for this, so hopefully it wont happen again 😅
