### ISSUE TITLE
Server list is always static

### ISSUE THREAD

**Issue by mateusmsant** [xandjiji/exevo-pan#162]
After selecting the PvP mode, the BattleEye status and the location, the server list still contains all the possible servers. Shouldn't it be a dynamic list, filtered by the three above inputs?

![image](https://user-images.githubusercontent.com/71290370/210588754-9b123547-aeee-4838-8fd1-c39902ce5f4c.png)

If Venebra was the only option it would lead to better UX, cause that's what I'm looking for, and we can already know it by the previous inputs

**Comment by xandjiji** [comment]
excellent suggestion, just released a new version with it 😄
