### ISSUE TITLE
add filter to search for specific quests

### ISSUE THREAD

**Issue by ddivito** [xandjiji/exevo-pan#17]
Can you add a filter to search for specific quests?

**Comment by ddivito** [comment]
https://tibiapy.readthedocs.io/en/latest/api.html#tibiapy.AuctionDetails.completed_quest_lines


```
completed_quest_lines

    The quest lines the character has fully completed.

    Type

        list of str

```

**Comment by xandjiji** [comment]
I might do it in the future

the only reason this isn't already available is because I'm avoiding to bloat too much the character data payload (which is already at 300kb):
https://exevopan-data.netlify.app/MinifiedCharacterData.json
