### ISSUE TITLE
More boss suggestions for “Recently appeared” section: Yakchal + Bank Robbery bosses

### ISSUE THREAD

**Issue by mathiasbynens** [xandjiji/exevo-pan#175]
It might be nice to include Yakchal in the list of interesting bosses to highlight when they’ve been killed, here:

<img width="349" alt="image" src="https://user-images.githubusercontent.com/81942/223641725-d2ce45d3-e96e-4be2-aa1c-ce803cc97616.png">

**Comment by xandjiji** [comment]
cool, I'll be adding this one too

**Comment by mathiasbynens** [comment]
Also, the Bank Robbery bosses:

- Elvira Hammerthrust
- Jesse the Wicked
- Mornenion
- Robby the Reckless
