### ISSUE TITLE
Boss Tracker stats for Feroxa are off

### ISSUE THREAD

**Issue by mathiasbynens** [xandjiji/exevo-pan#176]
Feroxa currently shows up with % chance on the 12th and 14th of each month, but in reality it’s more simple: Feroxa always spawns between the server save on the 13th and the server save on the 14th of each month. Unlike other bosses, we don’t need to look at historical kill data / time since the last kill. **Feroxa should only show up on one day per month, i.e. the 13th, with 100% chance.** Have you considered hardcoding an exception for her?

**Comment by xandjiji** [comment]
interesting, I'll try to fit this exception somewhere 😄
