### ISSUE TITLE
Soul War quest is not being filled

### ISSUE THREAD

**Issue by dayanfcosta** [xandjiji/exevo-pan#192]
Hi all, I realised that some chars does not appear with Soul War concluded even with the Revenant outfit unlocked, is this a bug?
An example: auctionId=1241209

**Comment by xandjiji** [comment]
yes, this is working as intended. The exevo pan quest list checks for completed quests in the "Completed Quest Lines" section of the bazaar page, which uses the same flags as in the game. Those flags are indeed very inconsistent 😅

for players interested in the soulwar rewards, you should check for the "Soul War available 💀" tag. This tag checks the revenant outfit to infer if the soulwar rewards are available.
