### ISSUE TITLE
Show item name on mouse hover

### ISSUE THREAD

**Issue by Wedz0ff** [xandjiji/exevo-pan#2]
Cipsoft adds on div title item name, i.e.:
`<div class="CVIcon CVIconObject" title="1,582x great fireball rune"></div>`

This would be a cool feature to have, specially for newcomers.

**Comment by xandjiji** [comment]
We used to have that in an earlier version of the project, but we removed since it increased the static file size by a lot (3MB~). In the future we might do a second try at that with a different aproach.
