### ISSUE TITLE
Error 404 recurrent

### ISSUE THREAD

**Issue by cirelly** [xandjiji/exevo-pan#215]
Greetings,

I come to report that when you try to access this url:
[error](https://www.exevopan.com/es?vocation=3)
The page loops between a 404 page and the main page.

I have the intuition that it is an error with the filters, routing, and querystring management.

**Comment by xandjiji** [comment]
our scripts are always making sure that our data is in sync with the official tibia website. Today the [worlds](https://www.tibia.com/community/?subtopic=worlds) page was inconsistent for a while (a few servers were missing) and that made our data also inconsistent. That made everything go boom

but it is now fixed :)

**Comment by cirelly** [comment]
Good job. 
I am a developer and passionate about tibia, if you like I can collaborate on this nice project 
:)
