### ISSUE TITLE
Correct missed bosses due to extra server save on 2024-07-30

### ISSUE THREAD

**Issue by mathiasbynens** [xandjiji/exevo-pan#228]
The Abomination spawned on Vunira @ 2024-07-30, but then wasn't killed because of the extra server save at 16:00~ CEST.

Is there any chance you could manually add an entry to the kill stats database so that 1) it stops showing up as "on chance" and 2) we can track the next spawn chance in 6 months? 

Maybe you could add a database entry as if 1 player died to the boss.

**Comment by xandjiji** [comment]
done 😛
