### ISSUE TITLE
Filter by min/max

### ISSUE THREAD

**Issue by eHonnef** [xandjiji/exevo-pan#25]
As the title said, filter the level not only by the Min value, but a max value, the same for skill.

Example: I want a low lvl with high skill.

**Comment by xandjiji** [comment]
nice idea, I'll try to implement a range slider like this:
[](https://material-ui.com/pt/components/slider/#range-slider)

**Comment by xandjiji** [comment]
This was added in our last major refactor (20f223756670fc5c2d9500a3f00a3c9b640b0b0b)
