### ISSUE TITLE
Add filter to know if Inquisition quest are completed

### ISSUE THREAD

**Issue by gabrielpsz** [xandjiji/exevo-pan#27]
It would be very useful if there have some filters to know about completed quests, like Inquisition, Children, and all other access like Scarlet and Oberon. But after read that the MinifiedCharacterData.json size could be a problem(is still?), I thought that if we have only a filter to Inquisition like the Soul War filter, it might fix the problem.

If you agreed, I could cooperate with you to develop some features as long as I have some specifications about the project limits.

And thanks for this application :)

**Comment by xandjiji** [comment]
it will definetely be implemented in the future!
